
class SensorSites:
    def __init__(self):
        self.lista = {
            "3552205": {"nome": "Sorocaba", "url": "https://notafiscal.sorocaba.sp.gov.br"},
            "3548708": {"nome": "São Bernardo do Campo", "url": "https://portal.gissonline.com.br/login/index.html"},
            "3513801": {"nome": "Diadema", "url": "https://portal.gissonline.com.br/login/index.html"},
            "3505708": {"nome": "Barueri", "url": "https://www.barueri.sp.gov.br/PMB/PortalServicos/WF/wfautenticacao.aspx?TpLogin=3&ReturnURL=/nfe/wfPrincipalNF.aspx"},
            "3509502": {"nome": "Campinas", "url": "https://novanfse.campinas.sp.gov.br/notafiscal/paginas/portal/index.html#/login"},
            "3550605": {"nome": "São Roque", "url": "https://saoroque.govbr.cloud/NFSe.Portal/"},
            "3521002": {"nome": "Iperó", "url": "https://ipero.jlsoft.com.br/Principal.aspx"},
            "3540606": {"nome": "Porto Feliz", "url": "https://portofeliz.govbr.cloud/NFSe.Portal/"},
            "2927408": {"nome": "Salvador", "url": "https://nfse.salvador.ba.gov.br"},
            "1302603": {"nome": "Manaus", "url": "https://nfse-prd.manaus.am.gov.br/nfse/servlet/hlogin"},
            "3550308": {"nome": "São Paulo", "url": "https://nfe.prefeitura.sp.gov.br/login.aspx"},
            "3304557": {"nome": "Rio de Janeiro", "url": "https://notacarioca.rio.gov.br/senhaweb/login.aspx"},
            "3522406": {"nome": "Itapeva", "url": "https://nfe.etransparencia.com.br/sp.itapeva/nfe/principal.aspx"},
            "4304606": {"nome": "Canoas", "url": "https://nfse.canoas.rs.gov.br/autenticacao/login"},
            "3548500": {"nome": "Santos", "url": "https://santos.giss.com.br/portal/home#/login-portal?pageRedirect=consultar-nfs"},
            "4305108": {"nome": "Caxias do Sul", "url": "https://nfse.caxias.rs.gov.br/autenticacao/login"},
            "3529005": {"nome": "Marilia", "url": "https://marilia.sigiss.com.br/marilia/contribuinte/login.php"},
            "3523909": {"nome": "Itu", "url": "https://itu.giss.com.br/portal/home#/login-portal"},
            "2304400": {"nome": "Fortaleza", "url": "https://idp2.sefin.fortaleza.ce.gov.br/realms/sefin/protocol/openid-connect/auth?nonce=e7266a6b-ce4f-4179-b401-e80129dcba49&response_type=code&client_id=iss.sefin.fortaleza.ce.gov.br&redirect_uri=https%3A%2F%2Fiss.fortaleza.ce.gov.br%2Fgrpfor%2Foauth2%2Fcallback&scope=openid+profile&state=secret-b9f49bee-82ce-4a02-b6fa-30bf3eea803d"},
            "5002704": {"nome": "Campo Grande", "url": "https://nfse.pmcg.ms.gov.br/NotaFiscal/index.php"},
            "3548807": {"nome": "São Caetano do sul", "url": "https://portal.gissonline.com.br/"},
            "3547809": {"nome": "Santo Andre", "url": "https://portal.gissonline.com.br/"},
            "2700805": {"nome": "Belem", "url": "http://siat.belem.pa.gov.br:8081/acesso/login.jsf"},
            "3525904": {"nome": "Jundiai", "url": "https://jundiai.giss.com.br/portal/#/login-portal"},
            "3518800": {"nome": "Guarulhos", "url": "https://portal.gissonline.com.br/login/index.html"},
            "3554102": {"nome": "Taubate", "url": "https://taubateiss.meumunicipio.digital/taubateiss/contribuinte/login.php?"},
            "4113700": {"nome": "Londrina", "url": "https://iss.londrina.pr.gov.br/contribuinte/login.php"},
            "2507507": {"nome": "Joao Pessoa", "url": "https://sispmjp.joaopessoa.pb.gov.br:8080/sispmjp/"},
            "3541000": {"nome": "Praia Grande", "url": "https://www.issnetonline.com.br/praiagrande/online/default/empresas.aspx"},
            "2408102": {"nome": "Natal", "url": "https://directa.natal.rn.gov.br/open.do?sys=DIR&a=wqf45tfes"},
            "4314902": {"nome": "Porto Alegre", "url": "https://decwebapp.portoalegre.rs.gov.br/issqn-e/inscricaoLista.seam?cid=1284"},
            "4115200": {"nome": "Maringa", "url": "https://maringa.fintel.com.br/"},
            "2611606": {"nome": "Recife", "url": "https://nfse.recife.pe.gov.br/senhaweb/login.aspx"},
            "4106902": {"nome": "Curitiba", "url": "https://isscuritiba.curitiba.pr.gov.br/iss/Principal/frmFramesPgPrincipal.aspx?sParam=MENSAGEM&sLogin=1"}
        }
